### ISSUE TITLE
ReferenceError: devices is not defined

### ISSUE THREAD

**Issue by IBMRob** [hardillb/node-red-contrib-wemo-ng#1]
Previously I had the nodes working but upgraded a number of packages (raspbian wheezy to Jessie upgrade) and now when I start node red it crashed with the following error:

<pre>
12 Dec 20:51:40 - ReferenceError: devices is not defined
    at subscribe (/home/convery/.node-red/node_modules/node-red-contrib-wemo-ng/WeMoNG.js:102:79)
    at null.<anonymous> (/home/convery/.node-red/node_modules/node-red-contrib-wemo-ng/WeMoNG.js:303:7)
    at emitOne (events.js:82:20)
    at emit (events.js:169:7)
    at /home/convery/.node-red/node_modules/node-red-contrib-wemo-ng/lib/wemo.js:186:13
    at Parser.<anonymous> (/home/convery/node_modules/xml2js/lib/xml2js.js:483:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (/home/convery/node_modules/xml2js/lib/xml2js.js:444:26)
    at emit (/home/convery/node_modules/sax/lib/sax.js:639:35)
</pre>

**Comment by IBMRob** [comment]
I've pulled down your latest code which i think had a some changes and its now loading up fine so will close this off.

(Can't say its working as I keep hitting the Wemo Wifi/3G bug)
